//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140310.1920 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.29 at 04:09:58 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://www.xmlunit.org/test/complexXml", xmlns = {
    @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "https://www.xmlunit.org/test/complexXml", prefix = "test")
})
package org.xmlunit.builder.jaxb;
